#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication surfaceFeatureExtract
runApplication surfaceTransformPoints -rotate "(0 0 1) 1" constant/triSurface/airfoil.stl constant/triSurface/airfoil.stl
runApplication surfaceFeatures


runApplication blockMesh

[ ! -d 0 ] && cp -r 0.orig 0

runApplication decomposePar -copyZero

runParallel snappyHexMesh -overwrite

runParallel patchSummary

runParallel potentialFoam

runParallel $(getApplication)

runApplication reconstructParMesh -constant

runApplication reconstructPar -latestTime

# ----------------------------------------------------------------- end-of-file
